services:
  - type: web
    name: bess-map
    env: python
    runtime: python-3.9
    plan: free  # Change to 'starter' for paid
    repo: https://github.com/your-username/Olympics_Map_1
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:server